language: go
go:
  - 1.6
  - 1.7
  - 1.8
  - tip

os:
  - linux

sudo: false
before_install:
  - mkdir -p /home/travis/gopath/{src,bin,pkg}
  - curl https://glide.sh/get | sh
install:
  - glide install
script:
  - $GOPATH/bin/goveralls -service=travis-ci
